/*
 * Featured Sweet Feet stock used when the live API is waking or unreachable.
 * Matches the backend seed catalogue so the shop never renders empty.
 */

export const FALLBACK_PRODUCTS = [
  {
    id: "sf-pro-grip",
    name: "Pro Grip Trainers",
    category: "trainers",
    gender: "unisex",
    price: 45000,
    oldPrice: 52000,
    rating: 4.3,
    ratingCount: 128,
    color: "black",
    badge: "top",
    badgeLabel: "TOP PICK",
    img: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
    sizes: [40, 41, 42, 43, 44],
    is_active: true,
    isActive: true,
    retailer_id: "lagos-kicks",
    retailerName: "Lagos Kicks Hub",
    retailerLocation: "Ikeja, Lagos",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Lagos+Kicks&background=160c02&color=f7dfb8&size=128&bold=true",
  },
  {
    id: "sf-urban-runners",
    name: "Urban Street Runners",
    category: "runners",
    gender: "men",
    price: 38500,
    oldPrice: 42000,
    rating: 4.5,
    ratingCount: 86,
    color: "white",
    badge: "new",
    badgeLabel: "NEW",
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    sizes: [41, 42, 43, 44, 45],
    is_active: true,
    isActive: true,
    retailer_id: "lagos-kicks",
    retailerName: "Lagos Kicks Hub",
    retailerLocation: "Ikeja, Lagos",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Lagos+Kicks&background=160c02&color=f7dfb8&size=128&bold=true",
  },
  {
    id: "sf-court-sneakers",
    name: "Classic Court Sneakers",
    category: "casual",
    gender: "unisex",
    price: 32000,
    oldPrice: 36000,
    rating: 4.1,
    ratingCount: 64,
    color: "white",
    badge: "top",
    badgeLabel: "TOP PICK",
    img: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    sizes: [39, 40, 41, 42, 43],
    is_active: true,
    isActive: true,
    retailer_id: "lagos-kicks",
    retailerName: "Lagos Kicks Hub",
    retailerLocation: "Ikeja, Lagos",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Lagos+Kicks&background=160c02&color=f7dfb8&size=128&bold=true",
  },
  {
    id: "sf-foam-runner",
    name: "Foam Runner Lite",
    category: "runners",
    gender: "unisex",
    price: 28000,
    oldPrice: 33000,
    rating: 4.2,
    ratingCount: 190,
    color: "multi",
    badge: "sale",
    badgeLabel: "SALE",
    img: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    sizes: [39, 40, 41, 42, 43, 44],
    is_active: true,
    isActive: true,
    retailer_id: "lagos-kicks",
    retailerName: "Lagos Kicks Hub",
    retailerLocation: "Ikeja, Lagos",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Lagos+Kicks&background=160c02&color=f7dfb8&size=128&bold=true",
  },
  {
    id: "sf-canvas-low",
    name: "Canvas Low-Top",
    category: "casual",
    gender: "unisex",
    price: 24500,
    oldPrice: null,
    rating: 4.0,
    ratingCount: 112,
    color: "white",
    badge: "",
    badgeLabel: "",
    img: "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=800&q=80",
    sizes: [39, 40, 41, 42, 43],
    is_active: true,
    isActive: true,
    retailer_id: "lagos-kicks",
    retailerName: "Lagos Kicks Hub",
    retailerLocation: "Ikeja, Lagos",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Lagos+Kicks&background=160c02&color=f7dfb8&size=128&bold=true",
  },
  {
    id: "sf-slide-sandals",
    name: "Slide Comfort Sandals",
    category: "sandals",
    gender: "women",
    price: 18500,
    oldPrice: null,
    rating: 4.4,
    ratingCount: 94,
    color: "brown",
    badge: "new",
    badgeLabel: "NEW",
    img: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80",
    sizes: [36, 37, 38, 39, 40],
    is_active: true,
    isActive: true,
    retailer_id: "lagos-kicks",
    retailerName: "Lagos Kicks Hub",
    retailerLocation: "Ikeja, Lagos",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Lagos+Kicks&background=160c02&color=f7dfb8&size=128&bold=true",
  },
  {
    id: "sf-oxford",
    name: "Classic Oxford",
    category: "corporate",
    gender: "men",
    price: 55000,
    oldPrice: null,
    rating: 4.8,
    ratingCount: 87,
    color: "brown",
    badge: "top",
    badgeLabel: "TOP PICK",
    img: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80",
    sizes: [40, 41, 42, 43, 44, 45],
    is_active: true,
    isActive: true,
    retailer_id: "abuja-style",
    retailerName: "Abuja Style Co",
    retailerLocation: "Wuse 2, Abuja",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Abuja+Style&background=c8440c&color=fff&size=128&bold=true",
  },
  {
    id: "sf-everyday-loafers",
    name: "EverDay Loafers",
    category: "loafers",
    gender: "unisex",
    price: 38500,
    oldPrice: null,
    rating: 4.7,
    ratingCount: 302,
    color: "black",
    badge: "top",
    badgeLabel: "BEST SELLER",
    img: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80",
    sizes: [38, 39, 40, 41, 42, 43],
    is_active: true,
    isActive: true,
    retailer_id: "abuja-style",
    retailerName: "Abuja Style Co",
    retailerLocation: "Wuse 2, Abuja",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Abuja+Style&background=c8440c&color=fff&size=128&bold=true",
  },
  {
    id: "sf-derby-brogue",
    name: "Derby Brogue",
    category: "corporate",
    gender: "men",
    price: 62000,
    oldPrice: null,
    rating: 4.6,
    ratingCount: 43,
    color: "brown",
    badge: "new",
    badgeLabel: "NEW",
    img: "https://images.unsplash.com/photo-1582897085656-c636d006a246?w=800&q=80",
    sizes: [40, 41, 42, 43, 44],
    is_active: true,
    isActive: true,
    retailer_id: "abuja-style",
    retailerName: "Abuja Style Co",
    retailerLocation: "Wuse 2, Abuja",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Abuja+Style&background=c8440c&color=fff&size=128&bold=true",
  },
  {
    id: "sf-chelsea-tan",
    name: "Chelsea Boot – Tan",
    category: "boots",
    gender: "men",
    price: 72000,
    oldPrice: null,
    rating: 4.8,
    ratingCount: 31,
    color: "brown",
    badge: "new",
    badgeLabel: "NEW",
    img: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80",
    sizes: [40, 41, 42, 43, 44, 45],
    is_active: true,
    isActive: true,
    retailer_id: "abuja-style",
    retailerName: "Abuja Style Co",
    retailerLocation: "Wuse 2, Abuja",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Abuja+Style&background=c8440c&color=fff&size=128&bold=true",
  },
  {
    id: "sf-ankle-midnight",
    name: "Ankle Boot – Midnight",
    category: "boots",
    gender: "women",
    price: 68000,
    oldPrice: 78000,
    rating: 4.9,
    ratingCount: 59,
    color: "black",
    badge: "sale",
    badgeLabel: "SALE",
    img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    sizes: [36, 37, 38, 39, 40, 41],
    is_active: true,
    isActive: true,
    retailer_id: "abuja-style",
    retailerName: "Abuja Style Co",
    retailerLocation: "Wuse 2, Abuja",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Abuja+Style&background=c8440c&color=fff&size=128&bold=true",
  },
  {
    id: "sf-espadrille",
    name: "Espadrille Mule",
    category: "sandals",
    gender: "women",
    price: 22000,
    oldPrice: 28000,
    rating: 4.0,
    ratingCount: 77,
    color: "brown",
    badge: "sale",
    badgeLabel: "SALE",
    img: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80",
    sizes: [36, 37, 38, 39, 40],
    is_active: true,
    isActive: true,
    retailer_id: "abuja-style",
    retailerName: "Abuja Style Co",
    retailerLocation: "Wuse 2, Abuja",
    retailerLogo:
      "https://ui-avatars.com/api/?name=Abuja+Style&background=c8440c&color=fff&size=128&bold=true",
  },
];
